FROM ubuntu:18.04

#Installing git and setting git user
#tioteo96/ubuntu:0.1
RUN \
	apt update &&\
	apt install git -y &&\
	git config --global user.name "Theo Song" &&\
	git config --global user.email "ohmytheo@gmail.com"


#Installing different versions of Java
#tioteo96/ubuntu:0.1.8
#RUN \
#	apt-get install openjdk-8-jdk -y

#tioteo96/ubuntu:0.1.11
RUN \
	apt-get install openjdk-11-jdk -y


#RUN \
#	apt install wget &&\
	
	
